@startuml
'https://plantuml.com/class-diagram

' - added class Criterion and derivatives that contains what's common of all
'   criteria, before in RandomForestClassifier

skinparam classAttributeIconSize 0
skinparam noteFontSize 11
'skinparam linetype ortho
'skinparam linetype polyline

class RandomForestClassifier {
- num_trees : int
- min_size : int
- max_depth : int
- ratio_samples : float
- num_random_features : float
- criterion : string
+ fit (X : float[][], y : float[])
+ predict (X : float[][]) : int[]
}

interface Node {
+ {abstract} predict(x : float[]) : int
}

class Leaf implements Node {
- label : int
+ predict(x : float[]) : int
}

class Parent implements Node {
- feature_index : int
- threshold : float
+ predict (x : float[]) : int
}

' associacions
RandomForestClassifier *-right-> "1..*" Node : decision_trees
Parent -down-> "1" Node : left_child
Parent -down-> "1" Node : right_child

' positionament
'RandomForestClassifier -[hidden]-> Node
@enduml